### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by akamob** [saramsv/decaying_human_body_part_classifier#1]
Hi, Thank you for the great work.

I want to learn more about your work, is there any papers or tutorials?

Any help is much appreciated!

**Comment by saramsv** [comment]
Hi! Thank you for your interest. I added the corresponding paper to the readme. Additional works on the topic are:
- [SChISM](https://openaccess.thecvf.com/content/WACV2021/papers/Mousavi_SChISM_Semantic_Clustering_via_Image_Sequence_Merging_for_Images_of_WACV_2021_paper.pdf)
- https://arxiv.org/pdf/2202.11900.pdf
- https://arxiv.org/pdf/2105.09975.pdf
- https://trace.tennessee.edu/utk_graddiss/7038/

**Comment by akamob** [comment]
Thank you!

If I have some new problems then I would contact you again:)

Best wishes.
